services:
  app:
    build: .
    network_mode: host

    env_file:
      - .env

    environment:
      DATA_DIR: /app/data
      DATABASE_URL: "file:/app/data/app.db"
      HEADLESS: "true"
      NODE_ENV: production

    volumes:
      - /var/services/web_packages/Job-mail-scrapper/data:/app/data

    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    network_mode: host

    command: tunnel run

    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}

    depends_on:
      - app

    restart: unless-stopped
